# Binomial Model

The binomial model depends on a few variables:

$u = $ Change in the 'up' state <br>
$d = $ Change in the 'down' state (commonly assumed to be $d=1/u$) <br>
$p_u = $ Probability of the up state <br>
$p_d = 1- p_u =$ Probability of the down state <br>

Using these variables, a tree of prices (and payoffs) are created to value the option in question. In this course, we will be using the Cox Ross Rubinstein method, which assumes:

$u = e^{\sigma \sqrt{\Delta t}}$<br>
$d = 1/u = e^{-\sigma \sqrt{\Delta t}}$<br>
$p_u = \frac{e^{r\Delta t}-d}{u-d}$ <br>
$p_d = 1-p_u$<br>
<br>
Where:

$r=$ Risk free rate <br>
$t=$ Time to maturity <br>
$\Delta t =$ Change in time for each step <br>
$\sigma=$ Asset volatility <br>

In [7]:
# graph a binomial payout tree for a stock

def binomial_tree(S, K, r, T, sigma, N):
    """
    Generate stock prices over time using a binomial model.
    
    Parameters:
    S : float : initial stock price
    K : float : strike price
    r : float : risk-free interest rate
    T : float : time to maturity
    sigma : float : volatility
    N : int : number of time steps
    
    Returns:
    np.ndarray : stock prices at each node
    """
    dt = T / N  # time step
    u = np.exp(sigma * np.sqrt(dt))  # up factor
    d = 1 / u  # down factor
    p = (np.exp(r * dt) - d) / (u - d)  # risk-neutral probability

    # Initialize the stock price tree
    stock_tree = np.zeros((N + 1, N + 1))
    stock_tree[0, 0] = S

    # Fill the stock price tree
    for i in range(1, N + 1):
        for j in range(i + 1):
            stock_tree[j, i] = S * (u ** (i - j)) * (d ** j)

    # Extract all possible paths
    paths = []
    for i in range(2 ** N):
        path = []
        current_price = S
        for j in range(N):
            if (i >> j) & 1:
                current_price *= u
            else:
                current_price *= d
            path.append(current_price)
        paths.append(path)

    return np.array(paths)

# Example usage
S = 100  # initial stock price
K = 100  # strike price
r = 0.05  # risk-free interest rate
T = 1  # time to maturity in years
sigma = 0.2  # volatility
N = 3  # number of time steps

stock_paths = binomial_tree(S, K, r, T, sigma, N)
print(stock_paths)

[[ 89.09472523  79.37870064  70.72223522]
 [112.24009024 100.          89.09472523]
 [ 89.09472523 100.          89.09472523]
 [112.24009024 125.97837858 112.24009024]
 [ 89.09472523  79.37870064  89.09472523]
 [112.24009024 100.         112.24009024]
 [ 89.09472523 100.         112.24009024]
 [112.24009024 125.97837858 141.39824581]]
